spring.application.name=api-rest-springbot
server.port=${SERVER_PORT:8080}

# Supabase Configuration
supabase.url=${SUPABASE_URL}
supabase.anon-key=${SUPABASE_ANON_KEY}
supabase.service-role-key=${SUPABASE_SERVICE_ROLE_KEY}

# Logging
logging.level.root=INFO
logging.level.com.example=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Spring WebFlux
spring.webflux.base-path=/api
